# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='Designates whether the user can log into this site.', verbose_name='staff status'),
        ),
    ]
