# Generated by Django 2.0.4 on 2018-08-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kidviz', '0020_auto_20180809_0826'),
        ('users', '0002_auto_20180108_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kidviz.Course'),
        ),
    ]
