# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 22:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kidviz', '0004_auto_20180117_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningconstructsublevelexample',
            name='sublevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples',
                                    to='kidviz.LearningConstructSublevel'),
        ),
    ]
