# Generated by Django 2.0.4 on 2018-04-09 03:02

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models

import kidviz.models


class Migration(migrations.Migration):
    dependencies = [
        ('kidviz', '0006_auto_20180409_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningConstructSublevelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified',
                 django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image', models.ImageField(upload_to=kidviz.models.UploadToPathAndRename('example_images/'))),
                ('order', models.IntegerField(default=0)),
                ('sublevel',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_images',
                                   to='kidviz.LearningConstructSublevel')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='learningconstructsublevelexample',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
