# Generated by Django 2.0.4 on 2018-04-09 03:17

from django.db import migrations, models

import kidviz.models


class Migration(migrations.Migration):
    dependencies = [
        ('kidviz', '0007_auto_20180409_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningconstructsublevelimage',
            name='sublevel',
        ),
        migrations.AddField(
            model_name='learningconstructsublevelexample',
            name='image',
            field=models.ImageField(blank=True, null=True,
                                    upload_to=kidviz.models.UploadToPathAndRename('example_images/')),
        ),
        migrations.DeleteModel(
            name='LearningConstructSublevelImage',
        ),
    ]
