# Generated by Django 2.0.4 on 2018-04-09 12:39

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('kidviz', '0008_auto_20180409_0317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningconstructsublevelexample',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='learningconstructsublevelexample',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
