# Generated by Django 2.0.4 on 2018-04-30 05:34

from django.db import migrations, models

import kidviz.models


class Migration(migrations.Migration):
    dependencies = [
        ('kidviz', '0012_auto_20180430_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='annotated_image',
        ),
        migrations.AddField(
            model_name='observation',
            name='annotation_data',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='original_image',
            field=models.FileField(blank=True, null=True,
                                   upload_to=kidviz.models.UploadToPathAndRename('original_images/')),
        ),
        migrations.AlterField(
            model_name='observation',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=kidviz.models.UploadToPathAndRename('videos/')),
        ),
        migrations.AlterField(
            model_name='observation',
            name='video_notes',
            field=models.FileField(blank=True, null=True,
                                   upload_to=kidviz.models.UploadToPathAndRename('video_notes/')),
        ),
    ]
