# Generated by Django 2.0.4 on 2018-08-03 06:23

import django.contrib.postgres.fields
from django.db import migrations, models


def set_default_tags(apps, schema_editor):
    Observation = apps.get_model('kidviz', 'Observation')

    observations = Observation.objects.all()
    for observation in observations:
        observation.tag_choices = list(observation.tags.all().values_list('id', flat=True))
        observation.save()


def reverse_set_default_tags(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('kidviz', '0016_auto_20180726_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='tag_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True,
                                                            default=[], null=True, size=None),
        ),
        migrations.RunPython(set_default_tags, reverse_set_default_tags),
    ]
