# Generated by Django 2.0.4 on 2018-08-09 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kidviz', '0019_observation_observation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
