# Generated by Django 2.0.4 on 2018-09-04 09:08
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations


def create_groups_and_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    administrators, _ = Group.objects.get_or_create(name='Administrators')

    AdminPerms = apps.get_model('kidviz', 'AdminPerms')
    emit_post_migrate_signal(2, False, 'default')  # this creates permissions

    Permission = apps.get_model('auth', 'Permission')
    administrators.permissions.add(Permission.objects.get(codename='can_approve_deny_users'))


class Migration(migrations.Migration):
    dependencies = [
        ('kidviz', '0021_adminperms'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions)
    ]
