# Generated by Django 2.0.4 on 2018-09-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kidviz', '0024_auto_20180904_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
