# Generated by Django 2.0.8 on 2019-01-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidviz', '0027_observation_no_constructs'),
    ]

    operations = [
        migrations.AddField(
            model_name='contexttag',
            name='curricular_focus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observation',
            name='curricular_focus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
