# Generated by Django 2.0.8 on 2019-03-02 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kidviz', '0028_auto_20190104_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='consented_to_research',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='learningconstructlevel',
            name='construct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='kidviz.LearningConstruct'),
        ),
        migrations.AlterField(
            model_name='learningconstructsublevel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublevels', to='kidviz.LearningConstructLevel'),
        ),
    ]
