# Generated by Django 2.0.8 on 2019-05-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidviz', '0030_auto_20190302_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
