# Generated by Django 2.2 on 2019-07-08 05:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidviz', '0031_observation_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='construct_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='observation',
            name='tag_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
