# Generated by Django 2.2 on 2019-07-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidviz', '0032_auto_20190708_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
