# Generated by Django 2.2 on 2019-09-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidviz', '0033_observation_external_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='image_width',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
