# Generated by Django 2.2.13 on 2020-12-02 11:11

from django.db import migrations


def fix_course(apps, schema_editor):
    Observation = apps.get_model('kidviz', 'Observation')
    observations = Observation.objects.all().prefetch_related(
        'students', 'constructs'
    ).filter(modified__gte='2020-11-18', modified__lte='2020-12-03')

    for observation in observations:
        student = observation.students.first()

        if not student:
            continue

        courses = set()

        for student in observation.students.all():
           for course in student.course_set.all():
               courses.add(course)

        if observation.course not in courses:
            for course in student.course_set.all():
                use_course = True

                for student in observation.students.all():
                    if course not in student.course_set.all():
                        use_course = False

                if use_course:
                    observation.course = course
                    continue

            observation.construct_choices = [construct.id for construct in observation.constructs.all()]
            observation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kidviz', '0035_setup'),
    ]

    operations = [
        migrations.RunPython(fix_course, reverse_code=migrations.RunPython.noop),
    ]
