# Generated by Django 2.2.13 on 2020-12-07 06:40

from django.db import migrations


def fix_constructs(apps, schema_editor):
    Observation = apps.get_model('kidviz', 'Observation')
    observations = Observation.objects.all().prefetch_related(
        'students', 'constructs'
    ).filter(created__lte='2020-11-18')

    for observation in observations:
        student = observation.students.first()

        if not student:
            continue

        courses = set()

        for student in observation.students.all():
           for course in student.course_set.all():
               courses.add(course)

        selected_course = None

        observation_year = observation.created.year

        # -1 before september so I can match course in the whole academic year
        # 2018 - 2019 for example
        if observation.created.month <= 8:
            observation_year -= 1

        for course in courses:
            if course.created.year == observation_year:
                selected_course = course

        if selected_course and observation.course != selected_course:
            observation.course = selected_course

        observation.construct_choices += [construct.id for construct in observation.constructs.all()]
        observation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kidviz', '0036_auto_20201202_1111'),
    ]

    operations = [
        migrations.RunPython(fix_constructs, reverse_code=migrations.RunPython.noop),
    ]
