# Generated by Django 2.2.13 on 2021-10-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidviz', '0037_auto_20201207_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
    ]
