# Generated by Django 2.0.4 on 2018-04-30 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsoa', '0010_contexttag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningconstructlevel',
            options={'ordering': ['level']},
        ),
        migrations.AlterModelOptions(
            name='learningconstructsublevel',
            options={'ordering': ['name']},
        ),
    ]
