# Generated by Django 2.0.4 on 2018-04-30 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsoa', '0011_auto_20180430_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='media',
            new_name='annotated_image',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='student_groups',
        ),
        migrations.AddField(
            model_name='observation',
            name='original_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lsoa.Observation'),
        ),
        migrations.AddField(
            model_name='observation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='lsoa.ContextTag'),
        ),
        migrations.AddField(
            model_name='observation',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='video_notes',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='observation',
            name='constructs',
            field=models.ManyToManyField(blank=True, to='lsoa.LearningConstructSublevel'),
        ),
    ]
