# Generated by Django 2.0.4 on 2018-05-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsoa', '0013_auto_20180430_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='annotation_data',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
