# Generated by Django 2.0.4 on 2018-07-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsoa', '0014_auto_20180514_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
