# Generated by Django 2.0.4 on 2018-08-06 12:50

import datetime
from django.db import migrations, models


def set_observation_date_to_created(apps, schema_editor):
    """
    Make `observation_date` for existing observation equals to `created`.
    There is assumption that observation is related to day it was created.
    """
    Observation = apps.get_model('lsoa', 'Observation')
    observations = Observation.objects.all()
    for observation in observations:
        observation.observation_date = observation.created
        observation.save()


def reverse_set_observation_date(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lsoa', '0016_auto_20180726_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='observation_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.RunPython(set_observation_date_to_created, reverse_set_observation_date)
    ]
