# Generated by Django 2.0.4 on 2018-08-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsoa', '0016_auto_20180726_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='contexttag',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
