# Generated by Django 2.0.4 on 2018-08-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsoa', '0017_observation_tag_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='contexttag',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
