# Generated by Django 2.0.4 on 2018-08-08 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsoa', '0017_observation_observation_date'),
        ('lsoa', '0018_contexttag_color'),
    ]

    operations = [
    ]
