# Generated by Django 2.0.4 on 2018-08-09 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lsoa', '0019_observation_observation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
