# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 19:25
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User as AuthUser


def create_groups(app, schema):
    au = ContentType.objects.get_for_model(AuthUser)

    # Teachers
    teachers_g, created = Group.objects.get_or_create(name='teachers')
    for x in [
        Permission.objects.create(codename='can_teach', name='Can Teach', content_type=au),

        Permission.objects.create(codename='can_add_quick_notes', name='Can Add QuickNotes', content_type=au),
        Permission.objects.create(codename='can_modify_quick_notes', name='Can modify QuickNotes', content_type=au),
        Permission.objects.create(codename='can_delete_quick_notes', name='Can delete QuickNotes', content_type=au),
    ]:
        teachers_g.permissions.add(x)

    # Admins
    admin_g, created = Group.objects.get_or_create(name='admins')
    for x in [
        Permission.objects.create(codename='can_add_students', name='Can Add Students', content_type=au),
        Permission.objects.create(codename='can_modify_students', name='Can Modify Students', content_type=au),
        Permission.objects.create(codename='can_delete_students', name='Can Delete Students', content_type=au),

        Permission.objects.create(codename='can_add_teachers', name='Can Add Teachers', content_type=au),
        Permission.objects.create(codename='can_modify_teachers', name='Can Modify Teachers', content_type=au),
        Permission.objects.create(codename='can_delete_teachers', name='Can Delete Teachers', content_type=au),

        Permission.objects.create(codename='can_add_groups', name='Can Add Groups', content_type=au),
        Permission.objects.create(codename='can_modify_groups', name='Can Modify Groups', content_type=au),
        Permission.objects.create(codename='can_delete_groups', name='Can Delete Groups', content_type=au),

        Permission.objects.create(codename='can_add_courses', name='Can Add Courses', content_type=au),
        Permission.objects.create(codename='can_modify_courses', name='Can Modify Courses', content_type=au),
        Permission.objects.create(codename='can_delete_courses', name='Can Delete Courses', content_type=au),

        Permission.objects.create(codename='can_add_construct_tags', name='Can Add Construct Tags', content_type=au),
        Permission.objects.create(codename='can_modify_construct_tags', name='Can Modify Construct Tags', content_type=au),
        Permission.objects.create(codename='can_delete_construct_tags', name='Can Delete Construct Tags', content_type=au),
    ]:
        admin_g.permissions.add(x)

    # Students
    students_g, created = Group.objects.get_or_create(name='students')
    permission = Permission.objects.create(codename='can_learn', name='Can Learn', content_type=au)
    students_g.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
