# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 19:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('losa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(related_name='student_courses', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(related_name='teacher_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
